In [1]:
import numpy as np

Regardons comment extraire des morceaux de tableau ou modifier seulement certaines parties d'un tableau. Pour cela nous
disposons de deux outils :
    
* l'extraction suivant les indices
* l'extraction suivant un filtre logique sur les valeurs

# Filtrer via les indices

On peut extraire des valeurs d'un tableau en fonction de ses indices comme on l'a fait pour les listes. Pour chaque dimension du tableau on peut indiquer

* la valeur de l'indice voulu (un entier)
* une liste d'indices `debut:fin:saut` avec par défaut `debut=0`, `fin=-1`, `saut=1`. Ainsi `1:10:2` veut dire les valeurs impaires entre 1 et 10. Le `saut` est optionel aussi `:` veut dire tous les indices.
* une liste d'indices explicite comme `[1,3,7]`

In [2]:
a = np.arange(12).reshape(3,4)
print(a, '\n')
print(a[1, :], '\n')       # 2nd line
print(a[0:2, 0:2], '\n')   # top left sub-matrix
print(a[::2, -1], '\n')    # even lines, last column
print(a[:, [0,-1]])        # first and last column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[4 5 6 7] 

[[0 1]
 [4 5]] 

[ 3 11] 

[[ 0  3]
 [ 4  7]
 [ 8 11]]


Il est ainsi possible d'indiquer qu'une opération ne s'applique qu'à un extrait du tableau en indiquant 
quels sont les cases du tableau qui seront modifiées :

In [3]:
a[::2, 1::2] += 100
a

array([[  0, 101,   2, 103],
       [  4,   5,   6,   7],
       [  8, 109,  10, 111]])

# Les filtres logiques

### Un filtre = une condition logique

Numpy permet d'extraire simplement les valeurs qui répondre à une condition logique.

Pour cela on utilise un filtre, à savoir un tableau booléen que l'on pose sur un tableau de même dimensions en imaginant que les cases True sont des fenêtres et False des murs. Le résultat est l'ensemble des valeurs qu'on voit à travers les fenêtres ordonnées par leur indice.

Le résultat est toujours un tableau en 1 dimension.

In [4]:
a = np.arange(12).reshape(3,4)
boole = a > 5    # a > 5 means all VALUES greater than 5
print(boole)
a[boole]         # apply the filter and show the result (1D array)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


array([ 6,  7,  8,  9, 10, 11])

Il est bien plus simple et lisible d'écrire la condition logique là où on met normalement les indices, à savoir entre les crochets :

In [5]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

### `where` pour gérer les valeurs hors filtre

Pour conserver la forme du tableau il est nécessaire de lui indiquer ce qu'il doit faire des valeurs qui ne remplissent pas la condition. Pour cela on utilise la fonction [`where`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html)  :

In [6]:
np.where(a > 5, a, 0)    # if a > 5 then a else 0

array([[ 0,  0,  0,  0],
       [ 0,  0,  6,  7],
       [ 8,  9, 10, 11]])

On peut faire tous les filtres imaginables qui donnent un tableau de booléan.

In [7]:
np.where(a%3 == 0, 2*a, -1)   # if a modulo 3 is 0 then 2 times a else -1

array([[ 0, -1, -1,  6],
       [-1, -1, 12, -1],
       [-1, 18, -1, -1]])

### Mettre à jour un tableau avec un filtre

Une autre facon  de conserver la forme du tableau consiste à modifier les valeurs qui correspondent au filtre.

Voici comment ajouter 100 à toutes les valeurs du tableau qui sont des carrés parfait ainsi qu'à la valeur 5 :

In [8]:
a[(np.round(np.sqrt(a)) - np.sqrt(a) == 0) | (a==5)] += 100  # | is OR (AND is &)
a

array([[100, 101,   2,   3],
       [104, 105,   6,   7],
       [  8, 109,  10,  11]])

{{ PreviousNext("np01 Numpy Introduction.ipynb", "np03 Manipulations.ipynb")}}