# Calcul matriciel

Numpy intègre le calcul matriciel (linear algebra) dans sa bibliothèque [numpy.linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html) mais [Scipy](https://docs.scipy.org/doc/scipy-1.1.0/reference/tutorial/linalg.html) aussi et mieux à savoir avec plus de fonctions et couplée à BLAS/LAPACK ce qui garanti une exécution nettement plus rapide si Numpy n'a pas été compilé avec cette option. Malheureusement il existe
deux fonctions dans la version que Numpy que Scipy n'a pas : `matrix_rank` et `cond` pour le conditionnement même s'il
existe une autre méthode dans ce dernier cas.

Aussi on utilise la version [linalg de Scipy](https://docs.scipy.org/doc/scipy/reference/linalg.html) mais parfois vous devrez passer à la version de Numpy...

In [1]:
import numpy as np
import scipy.linalg as lin
np.set_printoptions(precision=3)

### Opérations de base

On a vu que les opérateurs +, -, \* et /  sont appliqués terme à terme ce qui est juste pour + et - dans le cadre du calcul matriciel mais pas pour \* et /.

* Le __produit scalaire__ utilise la méthode `dot`
* La division que l'on peut imaginer comme 
   * la __résolution__ d'un système matriciel utilise la fonction `solve`
   * le calcul de l'__inverse__ de la matrice utilise la fonction `inv`

In [2]:
A = np.array([[1,2],[3,4]])
print("multiplication terme à terme : \n",A * A) # tous les opérateurs sont appliqués terme à terme
print("produit matriciel : \n", A.dot(A))        # A @ A can be used too

multiplication terme à terme : 
 [[ 1  4]
 [ 9 16]]
produit matriciel : 
 [[ 7 10]
 [15 22]]


Résolution de système matriciel :

In [3]:
b = np.array([17,37])
x = lin.solve(A, b) # bien mieux que de calculer la matrice inverse (plus rapide et plus stable)
print("x = ", x)
print("verfication : ", A.dot(x))

x =  [3. 7.]
verfication :  [17. 37.]


Mais si on le désire vraiment, on peut calculer la matrice inverse :

In [4]:
print("A⁻¹ :\n", lin.inv(A))       # la matrice inverse
print("x = ", lin.inv(A).dot(b))

A⁻¹ :
 [[-2.   1. ]
 [ 1.5 -0.5]]
x =  [3. 7.]


Enfin __la transposée__ est simplement `T` :

In [5]:
A.T

array([[1, 3],
       [2, 4]])

### Opérations sur la matrice

La bibliothèque offre des fonctions de

* décomposition (LU, Choleski, QR, SVD...)
* valeurs et vecteurs propres
* norme, déterminant, conditionnement et rang

In [6]:
Q,R = lin.qr(A)   # Q est orthogonale, R est triangulaire supérieur
print(Q, '\n\n', R)
print("\nVérification :\n", Q.dot(R))

[[-0.316 -0.949]
 [-0.949  0.316]] 

 [[-3.162 -4.427]
 [ 0.    -0.632]]

Vérification :
 [[1. 2.]
 [3. 4.]]


#### Valeurs propres et vecteurs propres

In [7]:
lin.eig(A) # donne les valeurs propres et les vecteurs propres de A

(array([-0.372+0.j,  5.372+0.j]), array([[-0.825, -0.416],
        [ 0.566, -0.909]]))

#### Déterminant, norme etc. 

In [8]:
print("Déterminant :", lin.det(A))
print("Norme 2 :", lin.norm(A), "\nNorme 1 :", lin.norm(A, 1) )
print("Conditionnement :", lin.expm_cond(A))  # utilise la norme 2, pour d'autres norme il faut utiliser numpy.linalg !

Déterminant : -2.0
Norme 2 : 5.477225575051661 
Norme 1 : 6.0
Conditionnement : 5.511586677311218


### Calculs matriciels avancés

Il est possible de calculer l'exponentiel d'une matrice et à partir de là, son log, sinus, cosinus... On a donc :

* `lin.expm(A)`
* `lin.logm(A)`
* `lin.sinm(A)`
* `lin.cosm(A)`
* `lin.tanm(A)`
* `lin.sinhm(A)`
* `lin.coshm(A)`
* `lin.tanhm(A)`

In [9]:
lin.expm(np.identity(3))

array([[2.718, 0.   , 0.   ],
       [0.   , 2.718, 0.   ],
       [0.   , 0.   , 2.718]])

{{ PreviousNext("np03 Manipulations.ipynb", "np05 Notation Einstein.ipynb")}}