## Calculs avec la notation d'Einstein

Cette notation permet d'exprimer de facon concise un nombre d'opération extraordinaire. Cette section n'est pas
nécessaire pour la suite mais c'est un exercice intellectuel intéressant.

L'idée est base est de sommer les termes d'une équation lorsqu'on y trouve 2 fois un même indice qui n'est pas défini par ailleurs. Ainsi :

$$ A_{i,i} \quad \textrm{veut dire} \quad \sum_{i=1}^N A_{i,i} \; \textrm{(la trace de la matrice)}$$

Si on regarde la multiplication matricielle $A\, B$ on a pour tout indice (i,j) du résultat :

$$ C_{i,j} = A_{i,k} \, B_{k,j} \quad \textrm{c.a.d} \quad  C_{i,j} = \sum_{k=1}^N A_{i,k} \, B_{k,j} $$ 

Le nom complet de la notation d'Einstein étant la convention de sommation d'Einstein, la fonction de numpy est [`einsum`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.einsum.html). Voici ce que cela donne pour nos 2 premiers exemples :

In [1]:
import numpy as np

A = np.arange(9).reshape(3,3)

print("Trace 'ii' : ", np.einsum('ii', A), '\n')   # 0 + 4 + 8 = 12

print("Multiplication matricielle A A 'ij,jk->ik' :")
print(np.einsum('ij,jk->ik', A, A))  # notez que j'ai nomé différement les indices

Trace 'ii' :  12 

Multiplication matricielle A A 'ij,jk->ik' :
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [2]:
A.dot(A)  # on vérifie

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

On note que les arguments de `einsum` sont :

* la règle de sommation dans une chaine de caractère avec une virgule pour séparer chaque composant
* les composants sur lesquels s'applique la règle

On peut aller un peu plus loin avec Numpy. Voici l'ensemble des règles qu'utilise `einsum` :

#### Règles de base et complémentaires

1. un indice répété implique une sommation sur cet indice sauf si cet indice est cité dans le résultat<br/>(cf exemple diagonale de A ci-dessous pour l'exception)
2. les indices qui se répètent d'un composant à un autre implique que les éléments référencés seront multiplié entre eux<br/> (cf exemple du produit matriciel)
3. un lettre omise dans le résultat (après `->`) implique que l'on sommme les éléments sur cet indice<br/> (cf exemple de la somme des éléments d'un vecteur ci-dessous)
4. si on ne met pas la flèche, einsum la met pour vous avec à droite tous les indices qui ne sont pas doublés rangé par ordre alphabétique<br/> (cf exemple de la transposée ci-dessous)

Voici une liste d'opérations prises sur le [blog du Dr Goulu](https://www.drgoulu.com/2016/01/17/einsum) :

<table align="center">
<tbody>
<tr>
<th>Signature de einsum</th>
<th>équivalent NumPy</th>
<th>Description</th>
</tr>
<tr>
<td><code>('i-&gt;', v)</code></td>
<td><code>sum(v)</code></td>
<td>somme des valeurs du vecteur v</td>
</tr>
<tr>
<td><code>('i,i-&gt;i', u, v)</code></td>
<td><code>u \* v</code></td>
<td>multiplication des vecteurs u et v élément par élément</td>
</tr>
<tr>
<td><code>('i,i', u, v)</code></td>
<td><code>inner(u, v)</code></td>
<td>produit scalaire de u et v</td>
</tr>
<tr>
<td><code>('i,j', u, v)</code></td>
<td><code>outer(u, v)</code></td>
<td>produit vectoriel de u et v</td>
</tr>
<tr>
<td><code>('ij', A)</code></td>
<td><code>A</code></td>
<td>renvoie la matrice A</td>
</tr>
<tr>
<td><code>('ji', A)</code></td>
<td><code>A.T</code></td>
<td>transposée de A</td>
</tr>
<tr>
<td><code>('ii-&gt;i', A)</code></td>
<td><code>diag(A)</code></td>
<td>diagonale de A</td>
</tr>
<tr>
<td><code>('ii', A)</code></td>
<td><code>trace(A)</code></td>
<td>somme de la diagonale de A</td>
</tr>
<tr>
<td class="tg-031e"><code>('ij-&gt;', A)</code></td>
<td class="tg-031e"><code>sum(A)</code></td>
<td class="tg-031e">somme des valeurs de A</td>
</tr>
<tr>
<td><code>('ij-&gt;j', A)</code></td>
<td><code>sum(A, axis=0)</code></td>
<td>somme des colonnes de A</td>
</tr>
<tr>
<td><code>('ij-&gt;i', A)</code></td>
<td><code>sum(A, axis=1)</code></td>
<td>somme des lignes de A</td>
</tr>
<tr>
<td><code>('ij,ij-&gt;ij', A, B)</code></td>
<td><code>A \* B</code></td>
<td>multiplication des matrices A et B élément par élément</td>
</tr>
<tr>
<td><code>('ij,ji-&gt;ij', A, B)</code></td>
<td><code>A \* B.T</code></td>
<td>multiplication des matrices A et B transposée élément par élément</td>
</tr>
<tr>
<td><code>('ij,jk', A, B)</code></td>
<td><code>dot(A, B)</code></td>
<td>produit scalaire de A et B</td> </tr>
<tr>
<td><code>('ij,jk-&gt;ij', A, B)</code></td>
<td><code>inner(A, B)</code></td>
<td>produit intérieur de A et B</td>
</tr>
<tr>
<td><code>('ij,jk-&gt;ijk', A, B)</code></td>
<td><code>A[:, None] \* B</code></td>
<td>chaque ligne de A multipliée par B</td>
</tr>
<tr>
<td><code>('ij,kl-&gt;ijkl', A, B)</code></td>
<td><code>A[:, :, None, None] \* B</code></td>
<td>chaque valeur de A multipliée par B</td>
</tr>
</tbody>
</table>

### Exercice

On va comparer les performances d'`einsum` et des fonctions Numpy correspondante. Pour cela calculez

* le cube de chaque élement d'un vecteur
* d'une matrice carrée, $A^3$,

avec `einsum` et sans. Comparer la vitesse d'exécution dans tous les cas avec 10000 éléments.

In [3]:
# a vous de jouer









Solution :

In [4]:
u = np.random.random(10000)

%timeit u*u*u
%timeit np.einsum('i,i,i->i', u,u,u)

11.5 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
15.2 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
A = u.reshape(100,100)

%timeit A.dot(A).dot(A)
%timeit np.einsum('ij,jk,kl->il', A, A, A)

138 µs ± 9.48 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
134 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


On constate qu'`einsum` est plus lent (\*). Mais en regardant sur le web on constate que cela n'a pas toujours été le cas et que c'est lié à la version de la bibliothèque Numpy. Conclusion si on veut de la performance, il faut tester son code avant pour choisir la méthode la plus rapide.

(\*) un peu plus lent pour le calcul vectoriel mais 1000 fois plus lent sur mon portable pour `A.dot(A)` (tous mes processeurs tournent à 100% alors que le calcul par `einsum` n'est fait que sur 1 seul processeur). La version `A.dot(A)` est nettement plus rapide grace à la bibliothèque MKL qu'utilise Numpy sur ma machine.

{{ PreviousNext("np03 Calcul matriciel.ipynb", "../lesson5 Scipy/sp01 Integration.ipynb")}}

On pourra aller directement à <a href="../lesson6 Pandas/pd01 -- Pandas indexing.ipynb">Pandas</a> pour les personnes 
qui ne sont pas intéressées par le calcul scientifique avec Scipy.